# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'ChatApp' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!
  
  # Ignore warning from pods
  inhibit_all_warnings!

  # Pods for ChatApp
  pod 'SnapKit'
  pod 'R.swift'
  pod 'Firebase/Firestore'
  pod 'FirebaseFirestoreSwift', '8.8.0-beta'
end
