desc "Run SwiftLint checks"
lane :run_linter do |options|
  swiftlint(
    ignore_exit_status: true,
    executable: "Pods/SwiftLint/swiftlint"
    )
end

desc "Install dependencies, clean and build project"
lane :build_for_testing do |options|
  cocoapods(try_repo_update_on_error: true)
  scan(
    clean: true, 
    build_for_testing: true
    )
end

desc "Run tests without building"
lane :run_tests do |options|
  scan(test_without_building: true)
end

desc "Build and test"
lane :build_and_test do |options|
  build_for_testing
  run_linter
  run_tests
end