desc "Clean and build for testing"
lane :build_for_testing do |options|
  scan(clean: true, build_for_testing: true)
end

desc "Run tests without building"
lane :run_tests do |options|
  scan(test_without_building: true)
end

desc "Clean, build and run tests"
lane :build_and_test do |options|
  build_for_testing
  run_tests
end