desc "Install dependencies, clean and build project"
lane :build_for_testing do |options|
  cocoapods(try_repo_update_on_error: true)
  scan(clean: true, build_for_testing: true)
end

desc "Run tests without building"
lane :run_tests do |options|
  scan(test_without_building: true)
end

desc "Clean, build and run tests"
lane :build_and_test do |options|
  build_for_testing
  run_tests
end