name: CI
on: [push, workflow_dispatch]
jobs:
  build-and-test:
    runs-on: macos-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Ruby setup
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 2.6
          bundler-cache: true
      - name: Build and run tests
        run: 
          bundle exec fastlane build_and_test